//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDBEntities5 : DbContext
    {
        public LibraryDBEntities5()
            : base("name=LibraryDBEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktor> Aktor { get; set; }
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Czasopismo> Czasopismo { get; set; }
        public virtual DbSet<Czytelnik> Czytelnik { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Ksiazka> Ksiazka { get; set; }
        public virtual DbSet<Praca_Naukowa> Praca_Naukowa { get; set; }
        public virtual DbSet<Slowo_Kluczowe> Slowo_Kluczowe { get; set; }
        public virtual DbSet<Wiadomosci> Wiadomosci { get; set; }
        public virtual DbSet<Wydawca> Wydawca { get; set; }
        public virtual DbSet<Wypozyczenia_Czasopisma> Wypozyczenia_Czasopisma { get; set; }
        public virtual DbSet<Wypozyczenia_Filmu> Wypozyczenia_Filmu { get; set; }
        public virtual DbSet<Wypozyczenia_Ksiazki> Wypozyczenia_Ksiazki { get; set; }
    }
}
